# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4c5aa67089f06bd8a3c78b5b27aeff58"
name = "ProfitPulse"
application_url = "https://marco-eagle-uncle-cricket.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "celaree-test.myshopify.com"

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products"
optional_scopes = [ "read_customers", "read_inventory" ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://marco-eagle-uncle-cricket.trycloudflare.com/api/auth/shopify/callback",
]
